version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
     - "9080:8080"
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "8075:80"
    depends_on:
      - app
